Private events with rails
felix-vondee/private_events pull request #1
Opened 2021-05-07 16:45 UTC by felix-vondee

In this project, we built a simple event creation and scheduling web app. Users can create events and other users can view event details and choose to attend. 

## Private-Events project features:

- Member can log in and create an event
- Anyone can see events created 
- Users can attend events

2021-05-07 21:01 UTC, henatan99 requested changes
# Changes Requested :recycle: 

Hi Team, great work so far. You have a few things to fix before your project gets approved.
 
## To Highlight 
- Most of the Model's associations are very good
- Light Controllers
- The app works very well on the browser except one bug
## To Improve 
- The date input field should have an appropriate input type with the data_select method, otherwise, users might enter the wrong text. See the attached screenshot and inline comment. 
![Screenshot from 2021-05-08 00-32-08](https://user-images.githubusercontent.com/64894927/117505365-92510e80-af8c-11eb-8fd1-fa75d41af2e8.png)
- You have to rename the Attendee table into appropriate name like Attendance or Attendation. Please check the inline comments

### Kindly make the requested changes and submit for another review

## Happy Coding :computer:

2021-05-07 21:01 UTC, henatan99 commented on app/views/events/_form.html.erb
> +    <%= f.input :date %>
Use form.date_select so that users can select from a standard calendar element

2021-05-07 21:01 UTC, henatan99 commented on app/models/attendee.rb
> +end
This tale should be named as Attendance or Attendation or something more descriptive. The attendee is a user itself, and it doesn't give sense to say Attendee belongs_to user.

2021-05-07 21:01 UTC, henatan99 commented on app/models/user.rb
> +  has_many :attended_events, through: :attendees, source: :event
This should be corrected as 
- has_many :attendances    # assuming you changes the Attendee table name to Attendances as commented below
- has_many :attended_events, through: :attendances

2021-05-07 21:01 UTC, henatan99 commented on app/models/attendee.rb
> +end
This tale should be named as Attendance or Attendation or something more descriptive. The attendee is a user itself, and it doesn't give sense to say Attendee belongs_to user.

2021-05-08 00:24 UTC, felix-vondee commented on app/views/events/_form.html.erb
> +    <%= f.input :date %>
Changes have been made. I used date_field instead. Date_select produced a hash after clicking "create event".

2021-05-08 00:24 UTC, felix-vondee commented on app/models/attendee.rb
> +end
Done

2021-05-08 00:50 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: 
---------
Hello  @felix-vondee Great job working on the required changes :clap: :+1: 
---------
Now you can merge this branch :muscle: :smile: 
HAPPY CODING !!! AND GOOD LUCK :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/117520369-7d18b780-af6d-11eb-9c94-0bcc22db3fd5.gif)

2021-05-08 01:10 UTC, merged